### ISSUE TITLE
Team Charter feedback 

### ISSUE THREAD

**Issue by Adamthe1st** [BibianaLee/Medsci-736#1]
Beautiful work you have done with your Team Charter Bibiana. I have found it nice and simple to follow. And it seems to me that you are ready for the Medsci736 journey! Just a few comments: 

**Project Name**: it would be clearer if the project’s name was the title ( i.e.  1st line of your team charter). 

**Vision:** I like how your vision statement is focused on gaining digital research skills. It seems to me that you clearly understand the differences vision and mission. Well done!

**Mission:** great work you did here Babiana, I love how detailed you were in defining your mission, especially your emphasis on flexibility and modification!  However, I was not sure what did you mean by “something” in the 1st bullet point. Also I would love to know what does “LPS” mean? 

**Behavioral & communication agreements**: both are good! I like the part about constructive feedback and feed forward. I think these highly determine the success of a project. 

**Project Team**: maybe add yourself in there too? Also, it would be great to  assign roles to team members (eg. project owner, scrum master etc..). probably add contact info (ie email) for each team member. 

---

Overall well done Babiana and good luck for rest of the course. Lets always help each other! We are one team :)

**Comment by BibianaLee** [comment]
Hi Ahmed, 

Thanks so much for the feedback :) I have amended my charter using your suggestions. 
I didn't add a scrum master but I did add myself and the contact info for the rest of the team. 

Do you think adding a scrum master is important?? If so I'll add one but I'm not quite sure who to pinpoint as the scrum master for the project. I guess Fabiana would be the scrum master??

**Comment by Adamthe1st** [comment]
Hi @BibianaLee, 
No worries! I am glad that you have found my feedback to be helpful. Regarding the assigning of roles, I think its important to add: 
1. your client - in my case, the supervisor is. (you may discuss with your supervisor if he/she would want to also be the "product owner"?).
1. Scrum master's role in my understanding:
   - Facilitates the link between the product owner and the development team. 
   - Removes any obstacles the team might be facing and help them self-manage
   - Makes sure the everyone is using scrum correctly. 
     so yes I think both Fabiana and Tanya would fit the role. Although I'd discuss it with them 1st. 
2. Members of your development team. This might include yourself, and whoever in the class that you might think will help you out including teaching staff and students.

I hope this helps. Let me know if I can help you with anything else Bibiana :)

**Comment by BibianaLee** [comment]
Hi Adam, 

Thanks for your response I forgot that this was here D: so sorry
I have amened my charter to include the scrum master as well as my mentor 

If you're ok with the changes could you please close this issue :) if not you can gimme more comments and I shall change them~

Kind Regards, 
Bibiana

**Comment by Adamthe1st** [comment]
Hi Bibiana, 
Your TeamCharter looks great! Good luck with the final assignment :)

Cheers 
Ahmed
